version: "3"

services:
  laundromat:
    build: .
    command: python manage.py run -h 0.0.0.0 -p 8080
    volumes:
      - .:/code
      - ./config:/config
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - BASE_URL=http://localhost:8080
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
