version: "3"

services:
  laundromat:
    build: .
    command: python manage.py run -h 0.0.0.0 -p 8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development