version: "3"

services:
  laundromat:
    build: .
    command: python manage.py run -h 0.0.0.0 -p 8080
    volumes:
      - .:/code
      - ./config:/config
    environment:
      - FLASK_ENV=development
      - OAUTHLIB_INSECURE_TRANSPORT=1
      - BASE_URL=https://localhost:8080
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
  proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
    depends_on:
      - laundromat
    volumes:
      - ./proxy/nginx.docker.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/localhost.crt:/etc/nginx/localhost.crt:ro
      - ./proxy/localhost.key:/etc/nginx/localhost.key:ro
    logging:
      driver: none
