version: 2

jobs:
  test:
    docker: 
      - image: circleci/python:3.8
    steps:
      - checkout
      - run: pip install --user -r requirements.txt
      - run: flake8

  build:
    docker:
      - image: circleci/python:3.8
    steps: 
      - setup_remote_docker
      - checkout
      - run: |
          docker build -t laundromat:${VERSION} .
          docker tag laundromat:${VERSION} laundromat:latest

notify:
  webhooks:
    - url: https://dwlnd1wnmh.execute-api.eu-west-2.amazonaws.com/prod/circleci/webhook

workflows:
  version: 2
  test_and_build:
    jobs:
      - test