version: 2

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Print Env Vars
          command: |
            printenv
     

  build:
    docker:
      - image: signalnoise/base:12
    steps:
      - setup_remote_docker
      - run:
          name: Message
          command: |
            echo hi
      
notify:
  webhooks:
    - url: https://dwlnd1wnmh.execute-api.eu-west-2.amazonaws.com/prod/circleci/webhook

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
